# Render Cron Jobs Configuration
# This file defines scheduled cron jobs for AudiaPro

# To deploy this cron job:
# 1. Create a new Cron Job in Render Dashboard
# 2. Connect your GitHub repository
# 3. Set the schedule and command below
# 4. Add environment variables (NEXT_PUBLIC_APP_URL)

jobs:
  - name: weekly-email-reports
    # Runs every Monday at 8:00 AM UTC
    schedule: "0 8 * * 1"
    # Command to trigger weekly reports via API
    command: |
      curl -X POST "${NEXT_PUBLIC_APP_URL}/api/admin/reports/weekly/send" \
        -H "Content-Type: application/json" \
        -H "X-Cron-Secret: ${CRON_SECRET}" \
        --fail --show-error

# Environment Variables Required:
# - NEXT_PUBLIC_APP_URL: Your deployed Next.js app URL (e.g., https://audiapro.vercel.app)
# - CRON_SECRET: Secret token to authenticate cron requests (optional, for security)

# Note: If using CRON_SECRET, update the API endpoint to verify this header
# in src/app/api/admin/reports/weekly/send/route.ts
