-- Create storage buckets for AudiaPro
-- Bucket 1: call-recordings (50MB limit, private)
-- Bucket 2: call-transcripts (5MB limit, private)
-- Bucket 3: call-analyses (2MB limit, private)

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('call-recordings', 'call-recordings', false, 52428800, ARRAY['audio/wav', 'audio/mpeg', 'audio/mp3', 'audio/x-wav']::text[]),
  ('call-transcripts', 'call-transcripts', false, 5242880, ARRAY['application/json']::text[]),
  ('call-analyses', 'call-analyses', false, 2097152, ARRAY['application/json']::text[])
ON CONFLICT (id) DO NOTHING;

-- Create storage policies for authenticated users
-- Allow authenticated users to access their tenant's files

-- Call recordings: Allow service role (worker) to upload, tenant users to download
CREATE POLICY "Service role can upload call recordings"
ON storage.objects FOR INSERT
TO service_role
WITH CHECK (bucket_id = 'call-recordings');

CREATE POLICY "Service role can read call recordings"
ON storage.objects FOR SELECT
TO service_role
USING (bucket_id = 'call-recordings');

CREATE POLICY "Service role can delete call recordings"
ON storage.objects FOR DELETE
TO service_role
USING (bucket_id = 'call-recordings');

-- Call transcripts: Similar policies
CREATE POLICY "Service role can upload call transcripts"
ON storage.objects FOR INSERT
TO service_role
WITH CHECK (bucket_id = 'call-transcripts');

CREATE POLICY "Service role can read call transcripts"
ON storage.objects FOR SELECT
TO service_role
USING (bucket_id = 'call-transcripts');

CREATE POLICY "Service role can delete call transcripts"
ON storage.objects FOR DELETE
TO service_role
USING (bucket_id = 'call-transcripts');

-- Call analyses: Similar policies
CREATE POLICY "Service role can upload call analyses"
ON storage.objects FOR INSERT
TO service_role
WITH CHECK (bucket_id = 'call-analyses');

CREATE POLICY "Service role can read call analyses"
ON storage.objects FOR SELECT
TO service_role
USING (bucket_id = 'call-analyses');

CREATE POLICY "Service role can delete call analyses"
ON storage.objects FOR DELETE
TO service_role
USING (bucket_id = 'call-analyses');

-- Note: Authenticated users will access files via signed URLs generated by the API
-- No need for direct storage policies for authenticated users
